app:
  image: ishaanpuniani/gameplatformserver
  links:
    - mongodb
    - ges
  volumes:
    - ./environment/GPSlogs:/var/log
  ports:
    - "8080:8080"
  environment:
    - MONGODB_URI=mongodb://mongodb:27017/gameplatformserver

ges:
  image: ishaanpuniani/gameexecutionserver
  volumes:
    - ./environment/GESlogs:/var/log
  ports:
    - "81:8080"

mongodb:
  image: mongo
  volumes:
    - ./environment/data/mongodb:/data/db
  ports:
    - "27017:27017"
  command: mongod --smallfiles
